version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: pouk_database
    restart: always
    environment:
      POSTGRES_DB: pouk_dbms
      POSTGRES_USER: authuright
      POSTGRES_PASSWORD: authuright
    ports:
      - "5432:5432"
    networks:
      - school_ms_system

  web:
    container_name: webserver
    build:
      context: ./server
    expose:
      - "5000"
    networks:
      - school_ms_system

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - school_ms_system

networks:
  school_ms_system:
    driver: bridge
