from marshmallow import Schema, fields

class StudentSchema(Schema):
    id = fields.Int()
    username = fields.Str()
    email = fields.Str()
    password = fields.Str()
    confirm = fields.Str()
    student_id = fields.Int()
    fname_kh = fields.Str()
    lname_kh = fields.Str()
    fname_en = fields.Str()
    lname_en = fields.Str()
    gender   = fields.Str()
    dob      = fields.Date()
    region   = fields.Str()
    grade_id = fields.Int()
    o_grade_id = fields.Int()
    roll = fields.Str()
    address = fields.Str()
    mother_name = fields.Str()
    father_name = fields.Str()
    number = fields.Str()
    email  = fields.Str()
    password = fields.Str()
    img = fields.Str()
    disc = fields.Str()
    status = fields.Bool()
    national_id = fields.Int()
    vaccine = fields.Bool()
    vaccine_id = fields.Int()
    admission_date = fields.Date()